name: Tests Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare to tests
        run: |         
          openssl enc -d -aes-256-ecb -in .github/tests.tar.gz -K 03E93092526619A03F4EC06B44ECA13E550E7D1630B2B3189AF6D3CBAE41A7BC -iter 7 | tar -xzf - -C ./src/
          npm i
          CI=true
      - name: Tests
        run: |
          npx react-scripts test
